### ISSUE TITLE
problems in

### ISSUE THREAD

**Issue by Lvhhhh** [Lornatang/WassersteinGAN_DIV-PyTorch#1]
in op"    real_gradient = torch.autograd.grad(
        outputs=real_outputs,
        inputs=real_data,
        grad_outputs=real_grad_outputs,
        create_graph=True,
        retain_graph=True,
        only_inputs=True,
        allow_unused=True,
    )[0]"
the size of tensor  grad_outputs(real_grad_outputs) should be the same as outputs(real_outputs).
if the size inputs(real_data) is different from them.
then you should add "allow_unused=True," otherwise it occur " One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior"
but if you add "allow_unused=True".the real_gradient  is None..do you have this problem?TXS

**Comment by Lornatang** [comment]
@Lvhhhh I will check it....

**Comment by Lornatang** [comment]
@Lvhhhh At present, this problem has been fixed in the latest version of the submission.

**Comment by Lvhhhh** [comment]
> @Lvhhhh At present, this problem has been fixed in the latest version of the submission.

what is the reason? where do you update to fixed this problem?

**Comment by Lvhhhh** [comment]
and i found in D_loss , errD_real is changed from "-torch.mean(real_output)" to "torch.mean(real_output)" , errD_fake is  changed from "torch.mean(fake_output)" to "-torch.mean(fake_output)" and errG is changed from "-torch.mean(fake_output)" to "torch.mean(fake_output)" , is that right?

**Comment by Lornatang** [comment]
Yeah
